### ISSUE TITLE
Environment Setup and Missing Code Issues

### ISSUE THREAD

**Issue by Xiong5Heng** [kwpoon/PPN-Pack#1]
Hi, 
Thanks for generously sharing your code. It is a great work and I am really interested in this paper and project.
However, I encountered some issues while trying to set up the environment and run the code:
1. I couldn't find the `environment.yml` file mentioned in the installation steps.
2. In the `demos_network.py file`, I couldn't locate the `get_high_res_object_heightmaps_and_occs()` function.
3. I was also wondering if it would be possible for you to release the training code. I would love to attempt training the model from scratch and possibly make some modifications to the network structure for further experimentation.

**Comment by Xiong5Heng** [comment]
And, the files downloaded from the link below are not the trained model, they are `.npy` files, not `.pt` files.
https://github.com/kwpoon/PPN-Pack/blob/56b2f50b96f3869af55a14e2669a683337d09007/README.md?plain=1#L45
I think there may be some mistakes.

**Comment by mangelini2** [comment]
Hi,
congratulations on your excellent work and thank you for sharing the code. 
I am also interested in this project but I was met with the same problems as @Xiong5Heng  when trying to test the code. 
I am guessing that the `environment.yml`  file can be taken from [SDF-Pack](https://github.com/kwpoon/SDF-Pack), but would it be possible to have access to the trained models and the location of the `get_high_res_object_heightmaps_and_occs()` function?

Thank you for your time and your contribution to the field.

**Comment by Xiong5Heng** [comment]
> Hi, congratulations on your excellent work and thank you for sharing the code. I am also interested in this project but I was met with the same problems as @Xiong5Heng when trying to test the code. I am guessing that the `environment.yml` file can be taken from [SDF-Pack](https://github.com/kwpoon/SDF-Pack), but would it be possible to have access to the trained models and the location of the `get_high_res_object_heightmaps_and_occs()` function?
> 
> Thank you for your time and your contribution to the field.

Hi, 
Did you solve the problem abolut the trained model?

**Comment by kwpoon** [comment]
Hi all,

Thanks for your interest. I've updated `README.md`, corrected the trained model link, and provided `environment.yml`.

In `demos_network.py`, the functions `save_all_object_heightmaps()` and the `get_high_res_object_heightmaps_and_occs()` are not actually called. They should be removed during code cleaning.

As for the training code, since it is currently used in some commercial-related projects, we will release it later. However, you can refer to the network structures in `ppnpack_models.py`.
